### PR TITLE
Remove things that now belong to the template repo

### PR DESCRIPTION
**Pull request by lhstrh**
This PR:
- [x] removes everything except the docs; and
- [x] simplifies the repository layout.

### CODE REVIEW

**Comment by edwardalee** [comment]
Wait, please don't remove all this.  Much of it will need adjustment to work in the template repo, so we need to keep this repo operational until everything has been migrated over.

**Comment by lhstrh** [comment]
Is there anything left that needs to be migrated, or get this be merged?

**Comment by edwardalee** [comment]
I've been removing things from main when I'm sure we don't need them anymore.
I just removed all the lf programs.

**Review by edwardalee — APPROVED** [review]
Actually, this looks good to merge.  We need the pico examples directory, but this seems to not get removed by this PR.

**Comment by lhstrh** [comment]
Still working on it...

**Comment by lhstrh** [comment]
In addition to removing all this stuff, we should move what is now in `./docs/src` to `./src`.

**Pull request merged**
